### ISSUE TITLE
Wonder.Woman.2017.720p.10bit.BluRay.6CH.x265.HEVC

### ISSUE THREAD

**Issue by FallingSnow** [erengy/anitomy#11]
Given `Wonder.Woman.2017.720p.10bit.BluRay.6CH.x265.HEVC`:
```
AnitomyElements {
  AnimeTitle: 'Wonder Woman 2017',
  FileExtension: 'mkv',
  FileName: 'Wonder.Woman.2017.720p.10bit.BluRay.6CH.sample',
  Source: 'BluRay',
  VideoResolution: '720p',
  VideoTerm: '10bit' }
```

Is it possible to identify 2017 as the ReleaseYear rather than part of the title?

**Comment by erengy** [comment]
Anitomy considers a number to be `AnimeYear` only if it's isolated within brackets, such as `(2017)`. This is to avoid parsing numbers that are actually a part of the title. *Blade Runner 2049* can be given as a recent example from non-anime media, though there are others from past years as well.

Also note that Anitomy is optimized toward anime releases, where release information is usually enclosed within brackets. Having issues with regular movies or TV series is to expected.

This issue is somewhat related to erengy/taiga#417.

**Comment by FallingSnow** [comment]
@Xtansia Do you think compiling to wasm is a good idea?
