### ISSUE TITLE
Anime recognition fails when anime title has a "."

### ISSUE THREAD

**Issue by soredake** [erengy/anitomy#20]
Notable example: the currently airing anime "NieR:Automata Ver1.1a"

recognition fails:
"NieR:Automata Ver1.1a - 01"

related: https://github.com/erengy/taiga/issues/1110

**Comment by erengy** [comment]
This happens because:

- `.` is a [delimiter](https://github.com/erengy/anitomy/blob/a4fa0a5604e988f6a4802a81c2d2649f98f99d93/anitomy/options.h#L18).
- `Ver1.1a` is tokenized into `Ver1`, `.`, `1a`.
- `1a` is a [partial episode pattern](https://github.com/erengy/anitomy/blob/a4fa0a5604e988f6a4802a81c2d2649f98f99d93/anitomy/parser_number.cpp#L342-L345), which is matched before `- 01`.

We could check the previous tokens (which is currently not possible), but that would most likely trade one edge case with another. So, not sure how to fix this at the moment.

**Comment by erengy** [comment]
Fixed in c71c5a3e510f967e2f6ac5905d4fccacf87ccb58.
