### ISSUE TITLE
Season-Episode in 3 digit semantics is wrong

### ISSUE THREAD

**Issue by acidhax** [erengy/anitomy#4]
Season 1, Episode 3: written as 103 is detected as Episode 103.

**Comment by erengy** [comment]
Simply put, that's a remarkably bad naming convention. If the filename says `103` without any other clues, it's just impossible to get that it actually means `S01E03`. The only reason a human can understand that is because they know *in advance* which series the file belongs to and how many episodes it has. Likewise, any program that makes use of Anitomy can always choose to reinterpret the number, if they have the same knowledge.

**Comment by acidhax** [comment]
Agreed it's enormously bad. It's still inhumanely common. Figured I'd give a heads up!
