### ISSUE TITLE
Suggestions/Issues

### ISSUE THREAD

**Issue by Vorror** [erengy/anitomy#6]
I'm not sure if you want all of my suggestions in 1 issue or multiple, but here are my suggestions/the things I've noticed:

- "Hi10" and "HEVC2" should be added as keywords.

- 00+00 Multiple episode pattern support. (e.g [HorribleSubs] Momokuri - 09+10 [720p].mkv)

- Support for basic roman numerals for volume patterns. (e.g Haikyuu!! Vol. III ) Maybe only support numbers 1-5 if you plan to store it as a keyword.

Nice to have:
- Support for "&" multiple episode patterns (e.g Dragon_Ball_Z_Movies_8_&_10_[720p,BluRay,DTS,x264]_-_THORA)
Although that may be a bit more involved and may require checking if the previous token(assuming current token is 8) is plural(Movies/Specials/Episodes), and then checking if the following token is a "connector" type of token(e.g "&" or ",") and if true gather every numerical token until we hit a known/delim token.

-Interesting?
[Infantjedi] Norn9 - Norn + Nonetto - 12 results in : "Norn9 - Norn   Nonetto" but that's such an edge case it can be ignored.

Wonderful library btw :+1:

**Comment by erengy** [comment]
Thanks for the suggestions!

> "Hi10" and "HEVC2" should be added as keywords.

Just looked them up at Nyaa. `Hi10` seems popular enough with multiple fansub groups using it. That said, is `HEVC2` really a thing? All releases with this keyword are uploaded by a single person, and searching Google for `HEVC2` yields nothing else.

> 00+00 Multiple episode pattern support. (e.g [HorribleSubs] Momokuri - 09+10 [720p].mkv)

Anitomy actually [supports this pattern](https://github.com/erengy/anitomy/blob/577070c6dfc5c88a35d5b60ca0e20eb5a79a7cda/anitomy/parser_number.cpp#L166), but the relevant function doesn't receive it as a single token due to `+` being a token delimiter. I think I'll need to define a special case for this.

> Support for basic roman numerals for volume patterns.

The parser currently relies on the assumption that the following token contains at least one digit, but it should be doable.

> Support for "&" multiple episode patterns

This is similar to the `+` issue, but more complicated. I'll see what I can do.

> [Infantjedi] Norn9 - Norn + Nonetto - 12 results in : "Norn9 - Norn Nonetto"

This may actually be fixed automatically if I can resolve the previous issue.

**Comment by Vorror** [comment]
Actually, you're right about HEVC2. I made a text dump of all anime filenames of nyaa to test the library and was reviewing each result. I didn't notice the uploader.

Thanks for looking into the other things :)

**Comment by Vorror** [comment]
As a heads up I ported anitomy to java: https://github.com/Vorror/anitomyJ :D
Quick question about your data.json file. Do you have actually have an automated unit test are do you simply check it visually? I ask because some entries differ than what's actually parsed. Example entries:
[ReDone] Memories Off 3.5 - 04 (DVD 10-bit).mkv (wrong eptitle/number)
Evangelion Shin Gekijouban Q (BDrip 1920x1080 x264 FLACx2 5.1ch)-ank.mkv (ank isn't enclosed therefore ignored)

Do you have some sort of test.cpp that's actually run against the json?

**Comment by Vorror** [comment]
As another heads up "[TaigaSubs]_Toradora!_(2008)_-_01v2_-_Tiger_and_Dragon_[1280x720_H.264_FLAC][1234ABCD].mkv" which is used in the README doesn't actually find the episode title anymore.

**Comment by erengy** [comment]
> I ported anitomy to java: https://github.com/Vorror/anitomyJ :D

That looks nice! I should probably add a list of similar projects to the README file some time.

> Quick question about your data.json file. Do you have actually have an automated unit test or do you simply check it visually? I ask because some entries differ than what's actually parsed.

I have two of them, actually. The first one is a console application that I use to test the contents of `data.json` or debug individual filenames. And the other is [like this](https://i.imgur.com/6m6kjNI.png), which helps me get a better look at things and check the performance of the library after every change I make. Both of them are quite messy, which is why I haven't committed them to the public repository.

Indeed, Anitomy returns different results for some entries. Most of them are problematic filenames that should be included in test cases in my opinion, but are ignored due to technical difficulties, etc.

> As another heads up "[TaigaSubs]_Toradora!_(2008)_-_01v2_-_Tiger_and_Dragon_[1280x720_H.264_FLAC][1234ABCD].mkv" which is used in the README doesn't actually find the episode title anymore.

Thanks for the heads up. I'll look into this as well.

**Comment by erengy** [comment]
577070c6df...c0687cb7d9 resolve these issues.

**Comment by Vorror** [comment]
Thanks!
